In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [4]:
pip install opencv-python

Defaulting to user installation because normal site-packages is not writeable
Collecting opencv-python
  Downloading opencv_python-5.0.0.93-cp37-abi3-win_amd64.whl.metadata (20 kB)
Requirement already satisfied: numpy>=2 in c:\programdata\anaconda3\lib\site-packages (from opencv-python) (2.1.3)
Downloading opencv_python-5.0.0.93-cp37-abi3-win_amd64.whl (44.0 MB)
   ---------------------------------------- 0.0/44.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/44.0 MB ? eta -:--:--
   ---------------------------------------- 0.3/44.0 MB ? eta -:--:--
   ---------------------------------------- 0.5/44.0 MB 1.1 MB/s eta 0:00:40
    --------------------------------------- 0.8/44.0 MB 1.3 MB/s eta 0:00:34
   - -------------------------------------- 1.3/44.0 MB 1.4 MB/s eta 0:00:31
   - -------------------------------------- 1.6/44.0 MB 1.5 MB/s eta 0:00:29
   - -------------------------------------- 2.1/44.0 MB 1.6 MB/s eta 0:00:26
   -- ------------------------------------- 2.6/44.0 MB 1.7 MB/s eta 0:00:24
   -- ------------------------------------- 3.1/44.0 MB 1.9 MB/s eta 0:00:22
   --- ------------------------------------ 3.7/44.0 MB 1.9 MB/s eta 0:00:22
   --- ------------------------------------ 3.9/44.0 MB 1.9 MB/s eta 0:00:21
   ---- ----------------------------------- 4.5/44.0 MB 1.9 MB/s eta 0:00:21
   ---- ----------------------------------- 5.0/44.0 MB 2.0 MB/s eta 0:00:20
   ---- ----------------------------------- 5.2/44.0 MB 2.0 MB/s eta 0:00:20
   ----- ---------------------------------- 5.5/44.0 MB 1.9 MB/s eta 0:00:20
   ----- ---------------------------------- 5.8/44.0 MB 1.9 MB/s eta 0:00:21
   ----- ---------------------------------- 6.0/44.0 MB 1.9 MB/s eta 0:00:21
   ----- ---------------------------------- 6.3/44.0 MB 1.9 MB/s eta 0:00:21
   ----- ---------------------------------- 6.6/44.0 MB 1.8 MB/s eta 0:00:21
   ------ --------------------------------- 6.8/44.0 MB 1.8 MB/s eta 0:00:21
   ------ --------------------------------- 7.1/44.0 MB 1.8 MB/s eta 0:00:21
   ------ --------------------------------- 7.3/44.0 MB 1.7 MB/s eta 0:00:22
   ------- -------------------------------- 7.9/44.0 MB 1.7 MB/s eta 0:00:22
   ------- -------------------------------- 8.1/44.0 MB 1.7 MB/s eta 0:00:22
   ------- -------------------------------- 8.4/44.0 MB 1.7 MB/s eta 0:00:22
   ------- -------------------------------- 8.7/44.0 MB 1.7 MB/s eta 0:00:22
   -------- ------------------------------- 8.9/44.0 MB 1.7 MB/s eta 0:00:22
   -------- ------------------------------- 9.2/44.0 MB 1.6 MB/s eta 0:00:22
   -------- ------------------------------- 9.4/44.0 MB 1.6 MB/s eta 0:00:22
   --------- ------------------------------ 10.0/44.0 MB 1.7 MB/s eta 0:00:21
   --------- ------------------------------ 10.5/44.0 MB 1.7 MB/s eta 0:00:20
   ---------- ----------------------------- 11.0/44.0 MB 1.7 MB/s eta 0:00:20
   ---------- ----------------------------- 11.8/44.0 MB 1.8 MB/s eta 0:00:19
   ----------- ---------------------------- 12.3/44.0 MB 1.8 MB/s eta 0:00:18
   ----------- ---------------------------- 13.1/44.0 MB 1.9 MB/s eta 0:00:17
   ------------ --------------------------- 13.4/44.0 MB 1.9 MB/s eta 0:00:17
   ------------ --------------------------- 14.2/44.0 MB 1.9 MB/s eta 0:00:16
   ------------- -------------------------- 14.7/44.0 MB 1.9 MB/s eta 0:00:16
   ------------- -------------------------- 15.2/44.0 MB 2.0 MB/s eta 0:00:15
   -------------- ------------------------- 16.0/44.0 MB 2.0 MB/s eta 0:00:15
   --------------- ------------------------ 16.5/44.0 MB 2.0 MB/s eta 0:00:14
   --------------- ------------------------ 17.0/44.0 MB 2.0 MB/s eta 0:00:14
   --------------- ------------------------ 17.6/44.0 MB 2.0 MB/s eta 0:00:14
   ---------------- ----------------------- 18.1/44.0 MB 2.0 MB/s eta 0:00:13
   ---------------- ----------------------- 18.6/44.0 MB 2.1 MB/s eta 0:00:13
   ----------------- ---------------------- 19.1/44.0 MB 2.1 MB/s eta 0:00:13
   ----------------- ---------------------- 19.7/44.0 MB 2.1 MB/s eta 0:00:12
   ------------------ --------------------- 20.2/44.0 MB 2.1 MB/s eta 0:00:12
   ------------------ --------------------- 20.7/44.0 MB 2.1 MB/s eta 0:00:12
   ------------------- -------------------- 21.0/44.0 MB 2.1 MB/s eta 0:00:11
   ------------------- -------------------- 21.5/44.0 MB 2.1 MB/s eta 0:00:11
   ------------------- -------------------- 21.8/44.0 MB 2.1 MB/s eta 0:00:11
   -------------------- ------------------- 22.3/44.0 MB 2.1 MB/s eta 0:00:11
   -------------------- ------------------- 22.5/44.0 MB 2.1 MB/s eta 0:00:11
   -------------------- ------------------- 23.1/44.0 MB 2.1 MB/s eta 0:00:11
   --------------------- ------------------ 23.6/44.0 MB 2.1 MB/s eta 0:00:10
   --------------------- ------------------ 24.1/44.0 MB 2.1 MB/s eta 0:00:10
   ---------------------- ----------------- 24.4/44.0 MB 2.1 MB/s eta 0:00:10
   ---------------------- ----------------- 24.9/44.0 MB 2.1 MB/s eta 0:00:10
   ---------------------- ----------------- 25.2/44.0 MB 2.1 MB/s eta 0:00:10
   ----------------------- ---------------- 25.7/44.0 MB 2.1 MB/s eta 0:00:09
   ----------------------- ---------------- 26.0/44.0 MB 2.1 MB/s eta 0:00:09
   ------------------------ --------------- 26.5/44.0 MB 2.1 MB/s eta 0:00:09
   ------------------------ --------------- 26.7/44.0 MB 2.1 MB/s eta 0:00:09
   ------------------------ --------------- 27.3/44.0 MB 2.1 MB/s eta 0:00:09
   ------------------------- -------------- 27.5/44.0 MB 2.1 MB/s eta 0:00:08
   ------------------------- -------------- 27.8/44.0 MB 2.1 MB/s eta 0:00:08
   ------------------------- -------------- 28.0/44.0 MB 2.1 MB/s eta 0:00:08
   ------------------------- -------------- 28.3/44.0 MB 2.0 MB/s eta 0:00:08
   -------------------------- ------------- 28.8/44.0 MB 2.0 MB/s eta 0:00:08
   -------------------------- ------------- 29.1/44.0 MB 2.0 MB/s eta 0:00:08
   -------------------------- ------------- 29.4/44.0 MB 2.0 MB/s eta 0:00:08
   -------------------------- ------------- 29.6/44.0 MB 2.0 MB/s eta 0:00:08
   --------------------------- ------------ 29.9/44.0 MB 2.0 MB/s eta 0:00:08
   --------------------------- ------------ 30.1/44.0 MB 2.0 MB/s eta 0:00:07
   --------------------------- ------------ 30.4/44.0 MB 2.0 MB/s eta 0:00:07
   --------------------------- ------------ 30.7/44.0 MB 2.0 MB/s eta 0:00:07
   ---------------------------- ----------- 30.9/44.0 MB 2.0 MB/s eta 0:00:07
   ---------------------------- ----------- 31.2/44.0 MB 2.0 MB/s eta 0:00:07
   ---------------------------- ----------- 31.5/44.0 MB 1.9 MB/s eta 0:00:07
   ---------------------------- ----------- 31.7/44.0 MB 1.9 MB/s eta 0:00:07
   ----------------------------- ---------- 32.0/44.0 MB 1.9 MB/s eta 0:00:07
   ----------------------------- ---------- 32.2/44.0 MB 1.9 MB/s eta 0:00:07
   ----------------------------- ---------- 32.5/44.0 MB 1.9 MB/s eta 0:00:06
   ----------------------------- ---------- 32.8/44.0 MB 1.9 MB/s eta 0:00:06
   ------------------------------ --------- 33.0/44.0 MB 1.9 MB/s eta 0:00:06
   ------------------------------ --------- 33.3/44.0 MB 1.9 MB/s eta 0:00:06
   ------------------------------ --------- 33.8/44.0 MB 1.9 MB/s eta 0:00:06
   ------------------------------ --------- 34.1/44.0 MB 1.9 MB/s eta 0:00:06
   ------------------------------- -------- 34.3/44.0 MB 1.9 MB/s eta 0:00:06
   ------------------------------- -------- 34.6/44.0 MB 1.9 MB/s eta 0:00:06
   ------------------------------- -------- 34.9/44.0 MB 1.9 MB/s eta 0:00:05
   ------------------------------- -------- 35.1/44.0 MB 1.9 MB/s eta 0:00:05
   -------------------------------- ------- 35.4/44.0 MB 1.9 MB/s eta 0:00:05
   -------------------------------- ------- 35.7/44.0 MB 1.9 MB/s eta 0:00:05
   -------------------------------- ------- 35.9/44.0 MB 1.8 MB/s eta 0:00:05
   -------------------------------- ------- 36.2/44.0 MB 1.8 MB/s eta 0:00:05
   --------------------------------- ------ 36.4/44.0 MB 1.8 MB/s eta 0:00:05
   --------------------------------- ------ 36.7/44.0 MB 1.8 MB/s eta 0:00:04
   --------------------------------- ------ 37.2/44.0 MB 1.8 MB/s eta 0:00:04
   ---------------------------------- ----- 37.7/44.0 MB 1.8 MB/s eta 0:00:04
   ---------------------------------- ----- 38.0/44.0 MB 1.8 MB/s eta 0:00:04
   ----------------------------------- ---- 38.5/44.0 MB 1.8 MB/s eta 0:00:03
   ----------------------------------- ---- 38.8/44.0 MB 1.8 MB/s eta 0:00:03
   ----------------------------------- ---- 39.1/44.0 MB 1.8 MB/s eta 0:00:03
   ----------------------------------- ---- 39.3/44.0 MB 1.8 MB/s eta 0:00:03
   ----------------------------------- ---- 39.6/44.0 MB 1.8 MB/s eta 0:00:03
   ------------------------------------ --- 39.8/44.0 MB 1.8 MB/s eta 0:00:03
   ------------------------------------ --- 40.1/44.0 MB 1.8 MB/s eta 0:00:03
   ------------------------------------ --- 40.4/44.0 MB 1.8 MB/s eta 0:00:03
   ------------------------------------ --- 40.6/44.0 MB 1.8 MB/s eta 0:00:02
   ------------------------------------- -- 40.9/44.0 MB 1.8 MB/s eta 0:00:02
   ------------------------------------- -- 41.2/44.0 MB 1.8 MB/s eta 0:00:02
   ------------------------------------- -- 41.4/44.0 MB 1.8 MB/s eta 0:00:02
   ------------------------------------- -- 41.7/44.0 MB 1.8 MB/s eta 0:00:02
   -------------------------------------- - 42.2/44.0 MB 1.8 MB/s eta 0:00:02
   -------------------------------------- - 42.5/44.0 MB 1.8 MB/s eta 0:00:01
   ---------------------------------------  43.0/44.0 MB 1.8 MB/s eta 0:00:01
   ---------------------------------------  43.3/44.0 MB 1.8 MB/s eta 0:00:01
   ---------------------------------------  43.8/44.0 MB 1.8 MB/s eta 0:00:01
   ---------------------------------------- 44.0/44.0 MB 1.8 MB/s eta 0:00:00
Installing collected packages: opencv-python
Successfully installed opencv-python-5.0.0.93
Note: you may need to restart the kernel to use updated packages.

In [5]:
pip install pillow

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pillow in c:\programdata\anaconda3\lib\site-packages (11.1.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import cv2
from PIL import Image

In [4]:
pip install pytorch-gradcam

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.

  DEPRECATION: Building 'pytorch-gradcam' using the legacy setup.py bdist_wheel mechanism, which will be removed in a future version. pip 25.3 will enforce this behaviour change. A possible replacement is to use the standardized build interface by setting the `--use-pep517` option, (possibly combined with `--no-build-isolation`), or adding a `pyproject.toml` file to the source tree of 'pytorch-gradcam'. Discussion can be found at https://github.com/pypa/pip/issues/6334

Collecting pytorch-gradcam
  Downloading pytorch-gradcam-0.2.1.tar.gz (6.0 MB)
     ---------------------------------------- 0.0/6.0 MB ? eta -:--:--
     ---------------------------------------- 0.0/6.0 MB ? eta -:--:--
     --- ------------------------------------ 0.5/6.0 MB 1.9 MB/s eta 0:00:03
     ------ --------------------------------- 1.0/6.0 MB 2.2 MB/s eta 0:00:03
     -------- ------------------------------- 1.3/6.0 MB 1.8 MB/s eta 0:00:03
     ------------ --------------------------- 1.8/6.0 MB 2.1 MB/s eta 0:00:03
     ------------- -------------------------- 2.1/6.0 MB 2.1 MB/s eta 0:00:02
     --------------- ------------------------ 2.4/6.0 MB 1.8 MB/s eta 0:00:02
     ------------------- -------------------- 2.9/6.0 MB 1.9 MB/s eta 0:00:02
     -------------------- ------------------- 3.1/6.0 MB 1.9 MB/s eta 0:00:02
     -------------------- ------------------- 3.1/6.0 MB 1.9 MB/s eta 0:00:02
     ------------------------ --------------- 3.7/6.0 MB 1.7 MB/s eta 0:00:02
     --------------------------- ------------ 4.2/6.0 MB 1.8 MB/s eta 0:00:02
     ------------------------------- -------- 4.7/6.0 MB 1.8 MB/s eta 0:00:01
     ---------------------------------- ----- 5.2/6.0 MB 1.9 MB/s eta 0:00:01
     ---------------------------------- ----- 5.2/6.0 MB 1.9 MB/s eta 0:00:01
     ---------------------------------- ----- 5.2/6.0 MB 1.9 MB/s eta 0:00:01
     -------------------------------------- - 5.8/6.0 MB 1.7 MB/s eta 0:00:01
     ---------------------------------------- 6.0/6.0 MB 1.7 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: opencv-python in c:\users\lenovo\appdata\roaming\python\python313\site-packages (from pytorch-gradcam) (5.0.0.93)
Requirement already satisfied: numpy in c:\programdata\anaconda3\lib\site-packages (from pytorch-gradcam) (2.1.3)
Building wheels for collected packages: pytorch-gradcam
  Building wheel for pytorch-gradcam (setup.py): started
  Building wheel for pytorch-gradcam (setup.py): finished with status 'done'
  Created wheel for pytorch-gradcam: filename=pytorch_gradcam-0.2.1-py3-none-any.whl size=5266 sha256=062f1369318f48c407f3a24ea218b76050d054d31a490a677de87aeea22e5307
  Stored in directory: c:\users\lenovo\appdata\local\pip\cache\wheels\c8\4b\b8\a39cb8137dbcb7e1a5bd3c7ec6250360ff2699eb1d4180ee3c
Successfully built pytorch-gradcam
Installing collected packages: pytorch-gradcam
Successfully installed pytorch-gradcam-0.2.1

In [6]:
pip install torch

Defaulting to user installation because normal site-packages is not writeable
Collecting torch
  Downloading torch-2.13.0-cp313-cp313-win_amd64.whl.metadata (39 kB)
Requirement already satisfied: filelock in c:\programdata\anaconda3\lib\site-packages (from torch) (3.17.0)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\programdata\anaconda3\lib\site-packages (from torch) (4.12.2)
Collecting setuptools>=77.0.3 (from torch)
  Downloading setuptools-83.0.0-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: sympy>=1.13.3 in c:\programdata\anaconda3\lib\site-packages (from torch) (1.13.3)
Requirement already satisfied: networkx>=2.5.1 in c:\programdata\anaconda3\lib\site-packages (from torch) (3.4.2)
Requirement already satisfied: jinja2 in c:\programdata\anaconda3\lib\site-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in c:\programdata\anaconda3\lib\site-packages (from torch) (2025.3.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\programdata\anaconda3\lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\programdata\anaconda3\lib\site-packages (from jinja2->torch) (3.0.2)
Downloading torch-2.13.0-cp313-cp313-win_amd64.whl (122.1 MB)
   ---------------------------------------- 0.0/122.1 MB ? eta -:--:--
   ---------------------------------------- 0.3/122.1 MB ? eta -:--:--
   ---------------------------------------- 0.8/122.1 MB 2.9 MB/s eta 0:00:43
   ---------------------------------------- 1.3/122.1 MB 2.7 MB/s eta 0:00:45
    --------------------------------------- 1.8/122.1 MB 2.8 MB/s eta 0:00:44
    --------------------------------------- 2.6/122.1 MB 2.9 MB/s eta 0:00:42
   - -------------------------------------- 3.4/122.1 MB 3.1 MB/s eta 0:00:39
   - -------------------------------------- 4.2/122.1 MB 3.2 MB/s eta 0:00:37
   - -------------------------------------- 5.0/122.1 MB 3.3 MB/s eta 0:00:36
   - -------------------------------------- 5.5/122.1 MB 3.3 MB/s eta 0:00:36
   -- ------------------------------------- 6.3/122.1 MB 3.2 MB/s eta 0:00:36
   -- ------------------------------------- 6.8/122.1 MB 3.2 MB/s eta 0:00:36
   -- ------------------------------------- 7.3/122.1 MB 3.2 MB/s eta 0:00:37
   -- ------------------------------------- 8.1/122.1 MB 3.1 MB/s eta 0:00:37
   -- ------------------------------------- 8.4/122.1 MB 3.1 MB/s eta 0:00:37
   -- ------------------------------------- 8.9/122.1 MB 3.1 MB/s eta 0:00:38
   --- ------------------------------------ 9.4/122.1 MB 3.0 MB/s eta 0:00:38
   --- ------------------------------------ 10.0/122.1 MB 3.0 MB/s eta 0:00:38
   --- ------------------------------------ 10.5/122.1 MB 2.9 MB/s eta 0:00:39
   --- ------------------------------------ 10.7/122.1 MB 2.8 MB/s eta 0:00:40
   --- ------------------------------------ 11.0/122.1 MB 2.8 MB/s eta 0:00:40
   --- ------------------------------------ 11.5/122.1 MB 2.7 MB/s eta 0:00:41
   --- ------------------------------------ 11.8/122.1 MB 2.7 MB/s eta 0:00:41
   --- ------------------------------------ 12.1/122.1 MB 2.6 MB/s eta 0:00:43
   ---- ----------------------------------- 12.3/122.1 MB 2.6 MB/s eta 0:00:43
   ---- ----------------------------------- 12.8/122.1 MB 2.6 MB/s eta 0:00:43
   ---- ----------------------------------- 13.1/122.1 MB 2.5 MB/s eta 0:00:43
   ---- ----------------------------------- 13.6/122.1 MB 2.5 MB/s eta 0:00:44
   ---- ----------------------------------- 13.9/122.1 MB 2.5 MB/s eta 0:00:44
   ---- ----------------------------------- 14.4/122.1 MB 2.5 MB/s eta 0:00:44
   ---- ----------------------------------- 14.9/122.1 MB 2.5 MB/s eta 0:00:44
   ----- ---------------------------------- 15.5/122.1 MB 2.5 MB/s eta 0:00:44
   ----- ---------------------------------- 16.0/122.1 MB 2.5 MB/s eta 0:00:44
   ----- ---------------------------------- 16.3/122.1 MB 2.5 MB/s eta 0:00:44
   ----- ---------------------------------- 16.8/122.1 MB 2.5 MB/s eta 0:00:43
   ----- ---------------------------------- 17.6/122.1 MB 2.5 MB/s eta 0:00:43
   ----- ---------------------------------- 18.1/122.1 MB 2.5 MB/s eta 0:00:42
   ------ --------------------------------- 18.4/122.1 MB 2.5 MB/s eta 0:00:42
   ------ --------------------------------- 19.1/122.1 MB 2.5 MB/s eta 0:00:42
   ------ --------------------------------- 19.7/122.1 MB 2.5 MB/s eta 0:00:42
   ------ --------------------------------- 20.2/122.1 MB 2.5 MB/s eta 0:00:41
   ------ --------------------------------- 20.7/122.1 MB 2.5 MB/s eta 0:00:41
   ------- -------------------------------- 21.5/122.1 MB 2.5 MB/s eta 0:00:40
Note: you may need to restart the kernel to use updated packages.
   ------- -------------------------------- 21.8/122.1 MB 2.5 MB/s eta 0:00:40
   ------- -------------------------------- 22.5/122.1 MB 2.5 MB/s eta 0:00:40
   ------- -------------------------------- 23.1/122.1 MB 2.5 MB/s eta 0:00:40
   ------- -------------------------------- 23.6/122.1 MB 2.5 MB/s eta 0:00:39
   ------- -------------------------------- 24.4/122.1 MB 2.6 MB/s eta 0:00:39
   -------- ------------------------------- 24.9/122.1 MB 2.6 MB/s eta 0:00:38
   -------- ------------------------------- 25.4/122.1 MB 2.6 MB/s eta 0:00:38
   -------- ------------------------------- 26.0/122.1 MB 2.6 MB/s eta 0:00:38
   -------- ------------------------------- 26.7/122.1 MB 2.6 MB/s eta 0:00:37
   --------- ------------------------------ 27.5/122.1 MB 2.6 MB/s eta 0:00:37
   --------- ------------------------------ 28.0/122.1 MB 2.6 MB/s eta 0:00:37
   --------- ------------------------------ 28.6/122.1 MB 2.6 MB/s eta 0:00:36
   --------- ------------------------------ 29.4/122.1 MB 2.6 MB/s eta 0:00:36
   --------- ------------------------------ 29.9/122.1 MB 2.6 MB/s eta 0:00:36
   --------- ------------------------------ 30.4/122.1 MB 2.6 MB/s eta 0:00:35
   ---------- ----------------------------- 30.9/122.1 MB 2.6 MB/s eta 0:00:35
   ---------- ----------------------------- 31.5/122.1 MB 2.6 MB/s eta 0:00:35
   ---------- ----------------------------- 32.0/122.1 MB 2.6 MB/s eta 0:00:35
   ---------- ----------------------------- 32.8/122.1 MB 2.6 MB/s eta 0:00:34
   ---------- ----------------------------- 33.3/122.1 MB 2.7 MB/s eta 0:00:34
   ----------- ---------------------------- 33.8/122.1 MB 2.7 MB/s eta 0:00:34
   ----------- ---------------------------- 34.1/122.1 MB 2.6 MB/s eta 0:00:34
   ----------- ---------------------------- 34.6/122.1 MB 2.6 MB/s eta 0:00:34
   ----------- ---------------------------- 35.4/122.1 MB 2.6 MB/s eta 0:00:33
   ----------- ---------------------------- 35.9/122.1 MB 2.6 MB/s eta 0:00:33
   ----------- ---------------------------- 36.4/122.1 MB 2.6 MB/s eta 0:00:33
   ----------- ---------------------------- 36.4/122.1 MB 2.6 MB/s eta 0:00:33
   ------------ --------------------------- 37.2/122.1 MB 2.6 MB/s eta 0:00:33
   ------------ --------------------------- 37.7/122.1 MB 2.6 MB/s eta 0:00:33
   ------------ --------------------------- 38.5/122.1 MB 2.6 MB/s eta 0:00:32
   ------------ --------------------------- 39.1/122.1 MB 2.6 MB/s eta 0:00:32
   ------------- -------------------------- 39.8/122.1 MB 2.6 MB/s eta 0:00:32
   ------------- -------------------------- 40.4/122.1 MB 2.7 MB/s eta 0:00:31
   ------------- -------------------------- 41.2/122.1 MB 2.7 MB/s eta 0:00:31
   ------------- -------------------------- 41.7/122.1 MB 2.7 MB/s eta 0:00:31
   ------------- -------------------------- 42.5/122.1 MB 2.7 MB/s eta 0:00:30
   -------------- ------------------------- 42.7/122.1 MB 2.7 MB/s eta 0:00:30
   -------------- ------------------------- 43.3/122.1 MB 2.7 MB/s eta 0:00:30
   -------------- ------------------------- 43.5/122.1 MB 2.7 MB/s eta 0:00:30
   -------------- ------------------------- 43.8/122.1 MB 2.6 MB/s eta 0:00:30
   -------------- ------------------------- 44.0/122.1 MB 2.6 MB/s eta 0:00:30
   -------------- ------------------------- 44.6/122.1 MB 2.6 MB/s eta 0:00:30
   -------------- ------------------------- 44.8/122.1 MB 2.6 MB/s eta 0:00:30
   -------------- ------------------------- 45.6/122.1 MB 2.6 MB/s eta 0:00:30
   -------------- ------------------------- 45.6/122.1 MB 2.6 MB/s eta 0:00:30
   --------------- ------------------------ 46.1/122.1 MB 2.6 MB/s eta 0:00:30
   --------------- ------------------------ 46.1/122.1 MB 2.6 MB/s eta 0:00:30
   --------------- ------------------------ 46.7/122.1 MB 2.6 MB/s eta 0:00:30
   --------------- ------------------------ 47.4/122.1 MB 2.6 MB/s eta 0:00:30
   --------------- ------------------------ 48.0/122.1 MB 2.6 MB/s eta 0:00:29
   --------------- ------------------------ 48.8/122.1 MB 2.6 MB/s eta 0:00:29
   ---------------- ----------------------- 49.3/122.1 MB 2.6 MB/s eta 0:00:29
   ---------------- ----------------------- 49.8/122.1 MB 2.6 MB/s eta 0:00:29
   ---------------- ----------------------- 50.6/122.1 MB 2.6 MB/s eta 0:00:28
   ---------------- ----------------------- 51.4/122.1 MB 2.6 MB/s eta 0:00:28
   ----------------- ---------------------- 51.9/122.1 MB 2.6 MB/s eta 0:00:27
   ----------------- ---------------------- 52.7/122.1 MB 2.6 MB/s eta 0:00:27
   ----------------- ---------------------- 53.2/122.1 MB 2.6 MB/s eta 0:00:27
   ----------------- ---------------------- 53.2/122.1 MB 2.6 MB/s eta 0:00:27
   ----------------- ---------------------- 54.0/122.1 MB 2.6 MB/s eta 0:00:27
   ----------------- ---------------------- 54.5/122.1 MB 2.6 MB/s eta 0:00:26
   ------------------ --------------------- 55.3/122.1 MB 2.6 MB/s eta 0:00:26
   ------------------ --------------------- 55.8/122.1 MB 2.6 MB/s eta 0:00:26
   ------------------ --------------------- 56.6/122.1 MB 2.6 MB/s eta 0:00:25
   ------------------ --------------------- 57.1/122.1 MB 2.6 MB/s eta 0:00:25
   ------------------ --------------------- 57.9/122.1 MB 2.6 MB/s eta 0:00:25
   ------------------- -------------------- 58.5/122.1 MB 2.6 MB/s eta 0:00:25
   ------------------- -------------------- 59.2/122.1 MB 2.6 MB/s eta 0:00:24
   ------------------- -------------------- 60.0/122.1 MB 2.7 MB/s eta 0:00:24
   ------------------- -------------------- 60.6/122.1 MB 2.7 MB/s eta 0:00:24
   -------------------- ------------------- 61.3/122.1 MB 2.7 MB/s eta 0:00:23
   -------------------- ------------------- 61.9/122.1 MB 2.7 MB/s eta 0:00:23
   -------------------- ------------------- 62.7/122.1 MB 2.7 MB/s eta 0:00:23
   -------------------- ------------------- 63.2/122.1 MB 2.7 MB/s eta 0:00:23
   -------------------- ------------------- 63.7/122.1 MB 2.7 MB/s eta 0:00:22
   --------------------- ------------------ 64.2/122.1 MB 2.7 MB/s eta 0:00:22
   --------------------- ------------------ 64.7/122.1 MB 2.7 MB/s eta 0:00:22
   --------------------- ------------------ 65.3/122.1 MB 2.7 MB/s eta 0:00:22
   --------------------- ------------------ 65.8/122.1 MB 2.7 MB/s eta 0:00:22
   --------------------- ------------------ 66.3/122.1 MB 2.7 MB/s eta 0:00:21
   --------------------- ------------------ 66.6/122.1 MB 2.7 MB/s eta 0:00:21
   --------------------- ------------------ 67.1/122.1 MB 2.7 MB/s eta 0:00:21
   ---------------------- ----------------- 67.4/122.1 MB 2.6 MB/s eta 0:00:21
   ---------------------- ----------------- 67.9/122.1 MB 2.6 MB/s eta 0:00:21
   ---------------------- ----------------- 68.2/122.1 MB 2.6 MB/s eta 0:00:21
   ---------------------- ----------------- 68.7/122.1 MB 2.6 MB/s eta 0:00:21
   ---------------------- ----------------- 68.9/122.1 MB 2.6 MB/s eta 0:00:21
   ---------------------- ----------------- 69.5/122.1 MB 2.6 MB/s eta 0:00:21
   ---------------------- ----------------- 69.7/122.1 MB 2.6 MB/s eta 0:00:21
   ----------------------- ---------------- 70.3/122.1 MB 2.6 MB/s eta 0:00:20
   ----------------------- ---------------- 70.5/122.1 MB 2.6 MB/s eta 0:00:20
   ----------------------- ---------------- 71.0/122.1 MB 2.6 MB/s eta 0:00:20
   ----------------------- ---------------- 71.3/122.1 MB 2.6 MB/s eta 0:00:20
   ----------------------- ---------------- 71.6/122.1 MB 2.6 MB/s eta 0:00:20
   ----------------------- ---------------- 72.1/122.1 MB 2.6 MB/s eta 0:00:20
   ----------------------- ---------------- 72.4/122.1 MB 2.6 MB/s eta 0:00:20
   ----------------------- ---------------- 72.6/122.1 MB 2.6 MB/s eta 0:00:20
   ----------------------- ---------------- 72.9/122.1 MB 2.6 MB/s eta 0:00:20
   ------------------------ --------------- 73.4/122.1 MB 2.6 MB/s eta 0:00:20
   ------------------------ --------------- 73.9/122.1 MB 2.6 MB/s eta 0:00:19
   ------------------------ --------------- 74.2/122.1 MB 2.5 MB/s eta 0:00:19
   ------------------------ --------------- 74.4/122.1 MB 2.5 MB/s eta 0:00:19
   ------------------------ --------------- 74.7/122.1 MB 2.5 MB/s eta 0:00:19
   ------------------------ --------------- 75.0/122.1 MB 2.5 MB/s eta 0:00:19
   ------------------------ --------------- 75.2/122.1 MB 2.5 MB/s eta 0:00:19
   ------------------------ --------------- 75.8/122.1 MB 2.5 MB/s eta 0:00:19
   ------------------------ --------------- 76.0/122.1 MB 2.5 MB/s eta 0:00:19
   ------------------------ --------------- 76.3/122.1 MB 2.5 MB/s eta 0:00:19
   ------------------------- -------------- 76.5/122.1 MB 2.5 MB/s eta 0:00:19
   ------------------------- -------------- 76.8/122.1 MB 2.5 MB/s eta 0:00:19
   ------------------------- -------------- 77.1/122.1 MB 2.5 MB/s eta 0:00:19
   ------------------------- -------------- 77.3/122.1 MB 2.4 MB/s eta 0:00:19
   ------------------------- -------------- 77.6/122.1 MB 2.4 MB/s eta 0:00:19
   ------------------------- -------------- 77.9/122.1 MB 2.4 MB/s eta 0:00:19
   ------------------------- -------------- 78.1/122.1 MB 2.4 MB/s eta 0:00:19
   ------------------------- -------------- 78.6/122.1 MB 2.4 MB/s eta 0:00:19
   ------------------------- -------------- 78.9/122.1 MB 2.4 MB/s eta 0:00:19
   -------------------------- ------------- 79.4/122.1 MB 2.4 MB/s eta 0:00:18
   -------------------------- ------------- 80.0/122.1 MB 2.4 MB/s eta 0:00:18
   -------------------------- ------------- 80.2/122.1 MB 2.4 MB/s eta 0:00:18
   -------------------------- ------------- 80.5/122.1 MB 2.4 MB/s eta 0:00:18
   -------------------------- ------------- 81.0/122.1 MB 2.4 MB/s eta 0:00:18
   -------------------------- ------------- 81.5/122.1 MB 2.4 MB/s eta 0:00:18
   -------------------------- ------------- 82.1/122.1 MB 2.4 MB/s eta 0:00:17
   --------------------------- ------------ 82.8/122.1 MB 2.4 MB/s eta 0:00:17
   --------------------------- ------------ 83.4/122.1 MB 2.4 MB/s eta 0:00:17
   --------------------------- ------------ 83.9/122.1 MB 2.4 MB/s eta 0:00:16
   --------------------------- ------------ 84.4/122.1 MB 2.4 MB/s eta 0:00:16
   --------------------------- ------------ 85.2/122.1 MB 2.4 MB/s eta 0:00:16
   ---------------------------- ----------- 85.7/122.1 MB 2.4 MB/s eta 0:00:15
   ---------------------------- ----------- 86.2/122.1 MB 2.4 MB/s eta 0:00:15
   ---------------------------- ----------- 87.0/122.1 MB 2.4 MB/s eta 0:00:15
   ---------------------------- ----------- 87.6/122.1 MB 2.4 MB/s eta 0:00:15
   ---------------------------- ----------- 88.1/122.1 MB 2.5 MB/s eta 0:00:14
   ----------------------------- ---------- 88.9/122.1 MB 2.5 MB/s eta 0:00:14
   ----------------------------- ---------- 89.4/122.1 MB 2.5 MB/s eta 0:00:14
   ----------------------------- ---------- 89.9/122.1 MB 2.5 MB/s eta 0:00:14
   ----------------------------- ---------- 90.4/122.1 MB 2.5 MB/s eta 0:00:13
   ----------------------------- ---------- 91.2/122.1 MB 2.5 MB/s eta 0:00:13
   ------------------------------ --------- 92.0/122.1 MB 2.5 MB/s eta 0:00:13
   ------------------------------ --------- 92.5/122.1 MB 2.5 MB/s eta 0:00:12
   ------------------------------ --------- 93.3/122.1 MB 2.5 MB/s eta 0:00:12
   ------------------------------ --------- 93.8/122.1 MB 2.5 MB/s eta 0:00:12
   ------------------------------- -------- 94.6/122.1 MB 2.5 MB/s eta 0:00:12
   ------------------------------- -------- 95.2/122.1 MB 2.5 MB/s eta 0:00:11
   ------------------------------- -------- 95.9/122.1 MB 2.5 MB/s eta 0:00:11
   ------------------------------- -------- 96.5/122.1 MB 2.5 MB/s eta 0:00:11
   ------------------------------- -------- 97.3/122.1 MB 2.5 MB/s eta 0:00:10
   -------------------------------- ------- 97.8/122.1 MB 2.5 MB/s eta 0:00:10
   -------------------------------- ------- 98.6/122.1 MB 2.5 MB/s eta 0:00:10
   -------------------------------- ------- 99.1/122.1 MB 2.5 MB/s eta 0:00:10
   -------------------------------- ------- 99.6/122.1 MB 2.5 MB/s eta 0:00:09
   -------------------------------- ------- 100.4/122.1 MB 2.5 MB/s eta 0:00:09
   --------------------------------- ------ 100.9/122.1 MB 2.5 MB/s eta 0:00:09
   --------------------------------- ------ 101.4/122.1 MB 2.5 MB/s eta 0:00:09
   --------------------------------- ------ 102.0/122.1 MB 2.5 MB/s eta 0:00:09
   --------------------------------- ------ 102.5/122.1 MB 2.5 MB/s eta 0:00:08
   --------------------------------- ------ 103.0/122.1 MB 2.5 MB/s eta 0:00:08
   --------------------------------- ------ 103.5/122.1 MB 2.5 MB/s eta 0:00:08
   ---------------------------------- ----- 104.1/122.1 MB 2.5 MB/s eta 0:00:08
   ---------------------------------- ----- 104.9/122.1 MB 2.5 MB/s eta 0:00:07
   ---------------------------------- ----- 105.1/122.1 MB 2.5 MB/s eta 0:00:07
   ---------------------------------- ----- 105.6/122.1 MB 2.5 MB/s eta 0:00:07
   ---------------------------------- ----- 106.2/122.1 MB 2.5 MB/s eta 0:00:07
   ---------------------------------- ----- 106.7/122.1 MB 2.5 MB/s eta 0:00:07
   ----------------------------------- ---- 107.0/122.1 MB 2.5 MB/s eta 0:00:07
   ----------------------------------- ---- 107.2/122.1 MB 2.5 MB/s eta 0:00:07
   ----------------------------------- ---- 107.7/122.1 MB 2.5 MB/s eta 0:00:06
   ----------------------------------- ---- 108.0/122.1 MB 2.5 MB/s eta 0:00:06
   ----------------------------------- ---- 108.3/122.1 MB 2.5 MB/s eta 0:00:06
   ----------------------------------- ---- 108.8/122.1 MB 2.4 MB/s eta 0:00:06
   ----------------------------------- ---- 109.1/122.1 MB 2.4 MB/s eta 0:00:06
   ----------------------------------- ---- 109.6/122.1 MB 2.4 MB/s eta 0:00:06
   ----------------------------------- ---- 109.8/122.1 MB 2.4 MB/s eta 0:00:06
   ------------------------------------ --- 110.4/122.1 MB 2.4 MB/s eta 0:00:05
   ------------------------------------ --- 111.1/122.1 MB 2.4 MB/s eta 0:00:05
   ------------------------------------ --- 111.7/122.1 MB 2.4 MB/s eta 0:00:05
   ------------------------------------ --- 112.2/122.1 MB 2.4 MB/s eta 0:00:05
   ------------------------------------ --- 112.7/122.1 MB 2.4 MB/s eta 0:00:04
   ------------------------------------- -- 113.0/122.1 MB 2.4 MB/s eta 0:00:04
   ------------------------------------- -- 113.5/122.1 MB 2.4 MB/s eta 0:00:04
   ------------------------------------- -- 114.0/122.1 MB 2.4 MB/s eta 0:00:04
   ------------------------------------- -- 114.6/122.1 MB 2.4 MB/s eta 0:00:04
   ------------------------------------- -- 115.1/122.1 MB 2.4 MB/s eta 0:00:03
   ------------------------------------- -- 115.6/122.1 MB 2.4 MB/s eta 0:00:03
   -------------------------------------- - 116.1/122.1 MB 2.4 MB/s eta 0:00:03
   -------------------------------------- - 116.7/122.1 MB 2.4 MB/s eta 0:00:03
   -------------------------------------- - 117.4/122.1 MB 2.4 MB/s eta 0:00:02
   -------------------------------------- - 118.0/122.1 MB 2.4 MB/s eta 0:00:02
   -------------------------------------- - 118.8/122.1 MB 2.4 MB/s eta 0:00:02
   ---------------------------------------  119.3/122.1 MB 2.5 MB/s eta 0:00:02
   ---------------------------------------  120.1/122.1 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------  120.3/122.1 MB 2.5 MB/s eta 0:00:01

  WARNING: The scripts torchfrtrace.exe and torchrun.exe are installed in 'C:\Users\Lenovo\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   ---------------------------------------- 2/2 [torch]

Successfully installed setuptools-83.0.0 torch-2.13.0

In [3]:
from torch.utils.data import Dataset
from sklearn.utils.class_weight import compute_class_weight

In [4]:
df= pd.read_csv("HAM10000_metadata.csv")

In [5]:
df.head()

     lesion_id      image_id   dx dx_type   age   sex localization
0  HAM_0000118  ISIC_0027419  bkl   histo  80.0  male        scalp
1  HAM_0000118  ISIC_0025030  bkl   histo  80.0  male        scalp
2  HAM_0002730  ISIC_0026769  bkl   histo  80.0  male        scalp
3  HAM_0002730  ISIC_0025661  bkl   histo  80.0  male        scalp
4  HAM_0001466  ISIC_0031633  bkl   histo  75.0  male          ear

In [6]:
df.isna().sum()

lesion_id        0
image_id         0
dx               0
dx_type          0
age             57
sex              0
localization     0
dtype: int64

In [8]:
import warnings
warnings.filterwarnings("ignore")

In [9]:
df["age"].fillna(df["age"].mean(), inplace=True)

In [10]:
df.isna().sum()

lesion_id       0
image_id        0
dx              0
dx_type         0
age             0
sex             0
localization    0
dtype: int64

In [11]:
df.describe()

                age
count  10015.000000
mean      51.863828
std       16.920252
min        0.000000
25%       40.000000
50%       50.000000
75%       65.000000
max       85.000000

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10015 entries, 0 to 10014
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   lesion_id     10015 non-null  object
 1   image_id      10015 non-null  object
 2   dx            10015 non-null  object
 3   dx_type       10015 non-null  object
 4   age           10015 non-null  float64
 5   sex           10015 non-null  object
 6   localization  10015 non-null  object
dtypes: float64(1), object(6)
memory usage: 547.8+ KB

In [17]:
print(df["dx"].unique())

['bkl' 'nv' 'df' 'mel' 'vasc' 'bcc' 'akiec']

In [18]:
disease_map = {
    'akiec': 0, 'bcc': 1, 'bkl': 2, 'df': 3, 'mel': 4, 'nv': 5, 'vasc': 6
}
df["target"]= df["dx"].map(disease_map)

In [19]:
df.head()

     lesion_id      image_id   dx dx_type   age   sex localization  target
0  HAM_0000118  ISIC_0027419  bkl   histo  80.0  male        scalp       2
1  HAM_0000118  ISIC_0025030  bkl   histo  80.0  male        scalp       2
2  HAM_0002730  ISIC_0026769  bkl   histo  80.0  male        scalp       2
3  HAM_0002730  ISIC_0025661  bkl   histo  80.0  male        scalp       2
4  HAM_0001466  ISIC_0031633  bkl   histo  75.0  male          ear       2

In [20]:
df.tail()

,lesion_id,image_id,dx,dx_type,age,sex,localization,target
10010,HAM_0002867,ISIC_0033084,akiec,histo,40.0,male,abdomen,0
10011,HAM_0002867,ISIC_0033550,akiec,histo,40.0,male,abdomen,0
10012,HAM_0002867,ISIC_0033536,akiec,histo,40.0,male,abdomen,0
10013,HAM_0000239,ISIC_0032854,akiec,histo,80.0,male,face,0
10014,HAM_0003521,ISIC_0032258,mel,histo,70.0,female,back,4

In [21]:
class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(df['target']),
    y=df['target']
)

In [23]:
import torch

In [24]:
class_weights_tensor = torch.tensor(class_weights, dtype=torch.float)

In [25]:
for idx, weight in enumerate(class_weights):
    class_name = list(disease_map.keys())[idx]
    print(f"Class {class_name} (Index {idx}): Weight = {weight:.4f}")

   Class akiec (Index 0): Weight = 4.3753
   Class bcc (Index 1): Weight = 2.7835
   Class bkl (Index 2): Weight = 1.3018
   Class df (Index 3): Weight = 12.4410
   Class mel (Index 4): Weight = 1.2855
   Class nv (Index 5): Weight = 0.2134
   Class vasc (Index 6): Weight = 10.0755

In [27]:
pip install torchvision

Defaulting to user installation because normal site-packages is not writeable
Collecting torchvision
  Downloading torchvision-0.28.0-cp313-cp313-win_amd64.whl.metadata (5.6 kB)
Requirement already satisfied: numpy in c:\programdata\anaconda3\lib\site-packages (from torchvision) (2.1.3)
Requirement already satisfied: torch==2.13.0 in c:\users\lenovo\appdata\roaming\python\python313\site-packages (from torchvision) (2.13.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\programdata\anaconda3\lib\site-packages (from torchvision) (11.1.0)
Requirement already satisfied: filelock in c:\programdata\anaconda3\lib\site-packages (from torch==2.13.0->torchvision) (3.17.0)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\programdata\anaconda3\lib\site-packages (from torch==2.13.0->torchvision) (4.12.2)
Requirement already satisfied: setuptools>=77.0.3 in c:\users\lenovo\appdata\roaming\python\python313\site-packages (from torch==2.13.0->torchvision) (83.0.0)
Requirement already satisfied: sympy>=1.13.3 in c:\programdata\anaconda3\lib\site-packages (from torch==2.13.0->torchvision) (1.13.3)
Requirement already satisfied: networkx>=2.5.1 in c:\programdata\anaconda3\lib\site-packages (from torch==2.13.0->torchvision) (3.4.2)
Requirement already satisfied: jinja2 in c:\programdata\anaconda3\lib\site-packages (from torch==2.13.0->torchvision) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in c:\programdata\anaconda3\lib\site-packages (from torch==2.13.0->torchvision) (2025.3.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\programdata\anaconda3\lib\site-packages (from sympy>=1.13.3->torch==2.13.0->torchvision) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\programdata\anaconda3\lib\site-packages (from jinja2->torch==2.13.0->torchvision) (3.0.2)
Downloading torchvision-0.28.0-cp313-cp313-win_amd64.whl (4.2 MB)
   ---------------------------------------- 0.0/4.2 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.2 MB ? eta -:--:--
   ------- -------------------------------- 0.8/4.2 MB 2.5 MB/s eta 0:00:02
   ------------ --------------------------- 1.3/4.2 MB 2.7 MB/s eta 0:00:02
   -------------------- ------------------- 2.1/4.2 MB 3.0 MB/s eta 0:00:01
   --------------------------- ------------ 2.9/4.2 MB 3.3 MB/s eta 0:00:01
   ----------------------------------- ---- 3.7/4.2 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------- 4.2/4.2 MB 3.5 MB/s eta 0:00:00
Installing collected packages: torchvision
Successfully installed torchvision-0.28.0
Note: you may need to restart the kernel to use updated packages.

In [28]:
import os
from torch.utils.data import Dataset, DataLoader, random_split
from torchvision import transforms

In [29]:
img_dir_1 = 'HAM10000_images_part_1'
img_dir_2 = 'HAM10000_images_part_2'

In [30]:
print(df.columns)

Index(['lesion_id', 'image_id', 'dx', 'dx_type', 'age', 'sex', 'localization',
       'target'],
      dtype='object')

In [31]:
class HAM10000Dataset(Dataset):
    def __init__(self, dataframe, transform=None):
        self.dataframe = dataframe
        self.transform = transform
        self.image_paths = {}
        
        
        for img_id in self.dataframe['image_id']:
            file_name = f"{img_id}.jpg"
            path_1 = f"{img_dir_1}/{file_name}"
            path_2 = f"{img_dir_2}/{file_name}"
            
            if os.path.exists(path_1):
                self.image_paths[img_id] = path_1
            elif os.path.exists(path_2):
                self.image_paths[img_id] = path_2
            else:
                print("img_missing!!!")

        print(f"Local dataset architecture ready. Managed images: {len(self.image_paths)}")

    def __len__(self):
        return len(self.dataframe)

    def __getitem__(self, idx):
        img_id = self.dataframe.iloc[idx]['image_id']
        label = self.dataframe.iloc[idx]['target']
        
        img_path = self.image_paths[img_id]
        image = Image.open(img_path).convert('RGB')
        
        if self.transform:
            image = self.transform(image)
            
        return image, label

In [32]:
train_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomVerticalFlip(p=0.5),
    transforms.RandomRotation(degrees=15),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

val_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(), # Clean, unaltered transformations for testing
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

In [33]:
train_size = int(0.8 * len(df))
val_size = len(df) - train_size

torch.manual_seed(42) # Keeps splits identical across runs
train_split, val_split = random_split(df, [train_size, val_size])

In [34]:
train_dataset = HAM10000Dataset(df.iloc[train_split.indices].reset_index(drop=True), transform=train_transform)
val_dataset = HAM10000Dataset(df.iloc[val_split.indices].reset_index(drop=True), transform=val_transform)


train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True, num_workers=0)
val_loader = DataLoader(val_dataset, batch_size=32, shuffle=False, num_workers=0)

print("\n--- PIPELINE SUCCESSFULLY BUILT ---")
print(f"Total Batches in Train Loader: {len(train_loader)} (~{len(train_dataset)} images)")
print(f"Total Batches in Val Loader:   {len(val_loader)} (~{len(val_dataset)} images)")

Local dataset architecture ready. Managed images: 8012
Local dataset architecture ready. Managed images: 2003

--- PIPELINE SUCCESSFULLY BUILT ---
Total Batches in Train Loader: 251 (~8012 images)
Total Batches in Val Loader:   63 (~2003 images)

In [35]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"System is routing computations to: {device}")

System is routing computations to: cpu

-----------------------------------MOVING TO GOOGLE COLAB------------------------------------